import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Datamite Technologies",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mx-auto max-w-7xl sm:px-6 lg:px-8">
          <div className="flex h-screen flex-col">
            <Header />
            <main className="flex-grow bg-gray-50 p-4">{children}</main>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
